spring:
  application:
    name: auth-server
  profiles:
    active: dev
  security:
    oauth2:
      client:
        registration:
          azure:
            provider: azure
            client-id: YOUR_CLIENT_ID_FROM_AZURE
            client-secret: YOUR_CLIENT_SECRET_FROM_AZURE
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - openid
              - profile
              - email
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/YOUR_TENANT_ID_FROM_AZURE/v2.0
