# ====================================================================
# Development-Specific Properties
# ====================================================================

app:
  login:
    # For development and local testing, we use standard form-based login by default.
    default-provider: form

spring:
  datasource:
    url: jdbc:h2:mem:authdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # In dev, we can allow hibernate to create/update the schema
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
